channels:
  - conda-forge
dependencies:
  - certifi
  - charset-normalizer
  - donfig
  - gisdata
  - git
  - netifaces
  - pip
  - pip:
    - geoserver-restconfig==2.0.16
    - posttroll==1.14.0
  - python=3.13
  - pyyaml
  - pyzmq
  - requests>=2.32.5
  - trollsift=1.0.0
  - urllib3>=2.6.0
  - zeromq
