channels:
  - conda-forge
dependencies:
  - certifi
  - charset-normalizer
  - donfig
  - gisdata
  - git
  - netifaces
  - pip
  - pip:
    - geoserver-restconfig==2.0.10
    - posttroll==1.10.0
  - python=3.11
  - pyyaml
  - pyzmq
  - requests>=2.32.0
  - trollsift=0.5.1
  - urllib3
  - zeromq
