channels:
  - conda-forge
dependencies:
  - python=3.11
  - pyzmq
  - pyyaml
  - trollsift=0.5.1
  - zeromq
  - gisdata
  - netifaces
  - requests
  - donfig
  - urllib3
  - certifi
  - charset-normalizer
  - git
  - pip
  - pip:
    - posttroll==1.10.0
    - geoserver-restconfig==2.0.10
