channels:
  - conda-forge
dependencies:
  - certifi
  - charset-normalizer
  - donfig
  - gisdata
  - git
  - netifaces
  - pip
  - pip:
    - geoserver-restconfig==2.0.14
    - posttroll==1.12.1
  - python=3.12
  - pyyaml
  - pyzmq
  - requests>=2.32.0
  - trollsift=0.5.3
  - urllib3>=2.2.2
  - zeromq
